# Asset Pack Configurations
[asset_pack]
	# Asset Pack Name
	name =				"ware"
	# Author
	author =			"DaSebsch"
	# Version
	version =			"0.0.1"

# Assets Files
[assets]
	# Maps
	[assets.maps]
		# MyMap = "MyFolder/MyAwesomeMap"
		# ...

	# Static Meshes
	[assets.static_meshes]
		# SM_Flower_01 = "MyFolder/SM_Awesome_Flower_01"
		# ...

	# Skeletal Meshes
	[assets.skeletal_meshes]
		# SK_Better_Man = "Characters/SK_BetterMan_03"
		# ...

	# Sounds
	[assets.sounds]
		WARE_Count1 = "audio/countdown_ann_sec1"
		WARE_Count2 = "audio/countdown_ann_sec2"
		WARE_Count3 = "audio/countdown_ann_sec3"
		WARE_Count4 = "audio/countdown_ann_sec4"
		WARE_Count5 = "audio/countdown_ann_sec5"
		WARE_Lose = "audio/game_lose_two"
		WARE_New = "audio/game_new_two"
		WARE_Prologue = "audio/game_prologue"
		WARE_Win = "audio/game_win_two"
		WARE_l1 = "audio/local_lose1"
		WARE_l2 = "audio/local_lose2"
		WARE_l3 = "audio/local_lose3"
		WARE_w1 = "audio/local_exo_won1"
		WARE_w2 = "audio/local_exo_won2"
		WARE_w3 = "audio/local_exo_won3"

	# Animations
	[assets.animations]
		# A_Character_Jump = "Animations/A_Character_Jump"
		# ...

	# Particles
	[assets.particles]
		# P_Big_Explosion = "Particles/P_Big_Explosion"
		# ...

	# Other Assets (for not yet categorized ones)
	[assets.others]
		# A_Audio_Rifle_Fire = "Audios/A_Audio_Rifle_Fire_03"
		# ...
