# Asset Pack Configurations
[asset_pack]
	# Asset Pack Name
	name =				"ware"
	# Author
	author =			""
	# Version
	version =			"1.0.0"

# Assets Files
[assets]
	# Maps
	[assets.maps]
		# MyMap = "MyFolder/MyAwesomeMap"
		# ...

	# Static Meshes
	[assets.static_meshes]
		# SM_Flower_01 = "MyFolder/SM_Awesome_Flower_01"
		# ...

	# Skeletal Meshes
	[assets.skeletal_meshes]
		# SK_Better_Man = "Characters/SK_BetterMan_3"
		# ...

	# Sounds
	[assets.sounds]
		achievement = "achievement"

	# Animations
	[assets.animations]
		# A_Character_Jump = "Animations/A_Character_Jump"
		# ...

	# Other Assets (for not yet categorized ones)
	[assets.others]
		# A_Audio_Rifle_Fire = "Audios/A_Audio_Rifle_Fire_03"
		# ...
